[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexer-derive = { path = "./lexer-derive" }
strum = { version = "0.24", features = ["derive"] }
